language: java
sudo: required
before_deploy:
- chmod 777 ./encrypts/deploy.sh
deploy:
- provider: script
  script: ./encrypts/deploy.sh
  on:
    branch: master
  skip_cleanup: true
before_install:
- tar -xzvf encrypts.tar.gz
- chmod 400 encrypts/key.pem
